version: '3.8'

services:
  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
      - ../html:/usr/share/nginx/html:ro